# API-first development with OpenAPI
# This file will be used at compile time to generate Spring-MVC endpoint stubs using openapi-generator
swagger: "2.0"
info:
  title: 'spots'
  version: 0.0.1

paths:
  /spots:
    get:
      tags:
        - "spot"
      summary: "Find spots using selectors"
      operationId: "findSpots"
      produces:
        - "application/xml"
        - "application/json"
      consumes:
        - "application/xml"
        - "application/json"
      parameters:

        - in: query
          name: limit
          required: true
          default: 100
          description: "page size"
          type: integer

        - in: query
          name: lastKey
          required: false
          description: "last evaluated key received from previous dynamoDB query"
          type: string

        - in: body
          name: filters
          required: true
          description: "spot query filters"
          schema:
            $ref: '#/definitions/SpotFilters'
      responses:
        200:
          description: "ok"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PagedSpotResponse"

    put:
      tags:
        - "spot"
      summary: "put spot"
      operationId: "putSpot"
      produces:
        - "application/xml"
        - "application/json"
      consumes:
        - "application/xml"
        - "application/json"

      parameters:
        - in: body
          name: spot
          required: true
          description: "spot model"
          schema:
            $ref: '#/definitions/Spot'

      responses:
        200:
          description: "object identifier"
          schema:
            type: integer
            format: int64

  /spots/filter-ids:
    get:
      tags:
        - "spot"
      summary: "Filter spot ids"
      operationId: "filterSpotIds"
      produces:
        - "application/xml"
        - "application/json"
      consumes:
        - "application/xml"
        - "application/json"
      parameters:
        - in: body
          name: filters
          required: true
          description: "spot query filters"
          schema:
            $ref: '#/definitions/SpotFilters'
      responses:
        200:
          description: "ok"
          schema:
            type: "array"
            items:
              type: "integer"
              format: "int64"
definitions:
  Spot:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Hel"
      photoUrls:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
      status:
        type: "string"
        description: "spot status, promoted by moderator"
        enum:
          - "DRAFT"
          - "DECLINED"
          - "AVAILABLE"

  PagedSpotResponse:
    type: "object"
    properties:
      spots:
        type: "array"
        items:
          $ref: "#/definitions/Spot"
      lastKey:
        type: "string"
        description: "last evaluated key received from previous dynamoDB query"
      limit:
        type: "integer"
        description: "queried page size"
      size:
        type: "integer"
        description: "items count"
      total:
        type: "integer"
        description: "total items count"

  SpotFilters:
    type: object
    properties:
      ids:
        description: "spot identifiers"
        required: true
        type: "array"
        items:
          type: "integer"
          format: "int64"
        collectionFormat: "multi"
      status:
        description: "status values"
        required: true
        type: "array"
        items:
          type: "string"
          enum:
            - "DRAFT"
            - "DECLINED"
            - "AVAILABLE"
          default: "available"
        collectionFormat: "multi"
