apiVersion: apps/v1
kind: Deployment
metadata:
    name: spot-service
spec:
    selector:
        matchLabels:
            app: spot-service
    replicas: 1
    template:
        metadata:
            labels:
                app: spot-service
        spec:
            containers:
                - name: spot-service
                  image: <X>
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - secretRef:
                            name: spot-dynamodb-secrets
                  env:
                      - name: GEO_HOST
                        value: geolocation-service:8080

---
apiVersion: v1
kind: Service
metadata:
    name: spot-service
spec:
    selector:
        app: spot-service
    ports:
        - name: http
          port: 8080
          targetPort: 8080
          protocol: TCP
    type: ClusterIP
